//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "4.4.1.9729")]
	internal sealed partial class Preferencias : global::System.Configuration.ApplicationSettingsBase {
		
		private static Preferencias defaultInstance = ((Preferencias)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Preferencias())));
		
		public static Preferencias Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string Usr_last_login {
			get {
				return ((string)(this["Usr_last_login"]));
			}
			set {
				this["Usr_last_login"] = value;
			}
		}
	}
}
